### ISSUE TITLE
アップデート内容のアイデア

### ISSUE THREAD

**Issue by hidenari-pixel** [orilab-server/lab-cloud#19]
## アイデア
今後のアップデートに盛り込んだら面白そうな機能を列挙
実現可能性は考慮せずご自由にどうぞ

**Comment by hidenariTakeuchi** [comment]
## 絶対欲しい
- 頻繁確認フォルダを任意に設定できるようにして, アップロード → 確認 → フィードバック → 修正&アップロード のやりとりをいちいちダウンロードしないでできるようにする → 詳細 : #20

**Comment by hidenariTakeuchi** [comment]
## あったほうが良さげ
- ドラッグ&ドロップによるアップロードをする際に, 特定のフォルダにカーソルを合わせた場合にそのフォルダ内にアップロードできる
- サイドメニューのフォルダ群は独自カスタマイズ可能にする(よく使用するフォルダなどを設定可能)

**Comment by hidenariTakeuchi** [comment]
## 面白そう

- 研究室HPのプロフィールをクラウドのアカウントと結びつけて, プロフィールを自由に変更可能

**Comment by taki-ser** [comment]
> ## 面白そう
> * 研究室HPのプロフィールをクラウドのアカウントと結びつけて, プロフィールを自由に変更可能

Hello world
