### ISSUE TITLE
頻繁確認フォルダ, やりとりを簡易化

### ISSUE THREAD

**Issue by hidenari-pixel** [orilab-server/lab-cloud#20]
## 問題
例えば, 卒論の添削を先生にお願いする場合に現在のクラウドを使用すると以下のようなフローを循環する

1. 学生が作成(修正)した文書をアップロード&先生に通知
2. 先生が文書をダウンロード
3. 先生がダウンロードした文書を確認, フィードバックを作成
4. 先生がフィードバック(と文書?)をアップロード&学生に通知
5. 学生がフィードバックをダウンロード
6. 学生がフィードバックを元に文書を修正
7. 1に戻る

これには以下の問題がある

- `アップロードとダウンロードの回数が多いこと`
- `アップロードした際に通知が飛ばない`

これでは, 結局メールを使用していた時代と大差がなくなってしまうため, これらの問題を解消する必要がある

## アイデア

アップロードする文書は, `PDF` or `Word`を想定

以前, 先生からWordファイルをWeb上で編集できないかというご意見を頂き, 調査してみた結果, [@syncfusion/ej2-react-documenteditor](https://github.com/syncfusion/ej2-react-ui-components) というReactでWordファイルが編集可能なライブラリを発見したが, 有償(maybe)のため除外。 また, [@cyntler/react-doc-viewer](https://github.com/cyntler/react-doc-viewer) というドキュメントファイル専用のviewerライブラリを発見したため, そちらの使用を検討。

やりとりのフローのアイデアは以下の通りである

1. 学生が作成した(修正)した文書をアップロード(自動通知)
2. 先生がWeb上で文書ファイルを参照
3. 先生が文書ファイルと同時に表示されるフィードバック記入用フォームにフィードバックを記入&送信(自動通知)
4. 学生がフィードバックファイルをダウンロード
5. 学生がフィードバックを元に文書を修正
6. 1に戻る

このフローでは詳細には以下の点で利便化を図ろうと考えている

- `通知の自動化`
- `先生のダウンロードなし(任意)`
- `学生側は既に存在しているファイルを削除する必要はなく, 修正でき次第アップロード可能(その際, 修正前のファイルは都度残り, 修正のヒストリーを残すようにする, 尚, 最新のアップロードを強調する)`

また, 上記フローでは記述していないが, 学生も文書ファイルの閲覧は可能にする(アップロード後にWebで確認できた方が対応速度が速くなると考えたため)

`※ あくまでアイデアの段階のため実現可能性は厳密に考慮していない`

**Comment by hidenariTakeuchi** [comment]
こんな感じで左側にPDF, 右側にコメント用のフォームが各ページに用意されている感じ

<img width="1412" alt="スクリーンショット 2022-12-07 19 09 30" src="https://user-images.githubusercontent.com/82199171/206150885-0bf1fc5b-c70c-468b-86aa-dc0c1a035112.png">

**Comment by hidenariTakeuchi** [comment]
- コメントのダウンロード機能は実装しなかった → メールでコメントの内容を通知するようにしたので
- PDFしか受け付けられない → 今後のバージョンアップで`pptx`, `docx`は受付できるように実装
