### ISSUE TITLE
[v1.1] 削除時一時避難ディレクトリを用意

### ISSUE THREAD

**Issue by hidenari-pixel** [orilab-server/lab-cloud#4]
ファイル・ディレクトリを削除した際, ゴミ箱ディレクトリのような場所に移動し, そこから削除した際に完全削除するようにする

ゴミ箱に格納されたファイル・フォルダの元の場所はDBで管理しておき, 完全削除する時&戻す時にテーブルから削除する

また, ゴミ箱内ではダウンロード, アップロード, リンク共有などの操作はできないようにする

ゴミ箱ディレクトリに移動されたファイル・フォルダは1ヶ月後に自動削除するようにする？

↓簡易的なテーブルの仕様↓
create table file_trashs (id, name, past_location, created_at)
create table folder_trashs (id, name, past_location, created_at)

**Comment by hidenariTakeuchi** [comment]
ついでに`request`エンドポイントのAPIも整理
